[bell]
duration = 0

[colors.bright]
black = "#767676"
blue = "#1a8fff"
cyan = "#14ffff"
green = "#23fd00"
magenta = "#fd28ff"
red = "#f2201f"
white = "#eeeeee"
yellow = "#fffd00"

[colors.normal]
black = "#000000"
blue = "#0d73cc"
cyan = "#0dcdcd"
green = "#19cb00"
magenta = "#cb1ed1"
red = "#cc0403"
white = "#d0d0d0"
yellow = "#cecb00"

[colors.primary]
background = "#000000"
foreground = "#d0d0d0"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 22

[font.bold]
family = "Comic Shanns"
style = "Regular"

[font.bold_italic]
family = "Comic Shanns"
style = "Regular"

[font.italic]
family = "Comic Shanns"
style = "Regular"

[font.normal]
family = "Comic Shanns"
style = "Regular"

[font.offset]
x = 1
y = 1

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[mouse]
hide_when_typing = true

[scrolling]
history = 0

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "Full"
opacity = 1.0

[window.dimensions]
columns = 100
lines = 40

[window.padding]
x = 4
y = 4

[general]
live_config_reload = true
